name: Moroccan Rubyist
description: Free Ruby and Rails tutorials for Moroccan Rubyists.
url: http://moroccanrubyist.com
markdown: redcarpet
highlighter: pygments
paginate: 10
permalink: /:categories/:title/